services:
  api:
    build: 
      context: ./api
      dockerfile: Containerfile
    command: npm run dev
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./.env.local:/app/.env.local
    ports:
      - "4000:4000"
    env_file:
      - .env.local
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
      target: builder
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FORCE_COLOR=1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - ./.env.local:/app/.env.local
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - api
    restart: unless-stopped 