[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Containerfile"

[deploy]
startCommand = "cd api && node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 