[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node --max-old-space-size=1024 index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production" 