name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build API Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: false

      - name: Build Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: false
